//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientEntity
    {
        public IngredientEntity()
        {
            this.RecipeDetailsEntities = new HashSet<RecipeDetailsEntities>();
        }
    
        public int NDB_No { get; set; }
        public string Shrt_Desc { get; set; }
        public Nullable<decimal> Water_g { get; set; }
        public Nullable<int> Energ_Kcal { get; set; }
        public Nullable<decimal> Protein_g { get; set; }
        public Nullable<decimal> Lipid_Tot_g { get; set; }
        public Nullable<decimal> Carbohydrt_g { get; set; }
        public Nullable<decimal> Fiber_TD_g { get; set; }
        public Nullable<decimal> Sugar_Tot_g { get; set; }
        public Nullable<decimal> FA_Sat_g { get; set; }
        public Nullable<decimal> FA_Mono_g { get; set; }
        public Nullable<decimal> FA_Poly_g { get; set; }
        public Nullable<int> Cholestrl_mg { get; set; }
        public Nullable<decimal> GmWt_1 { get; set; }
        public string GmWt_Desc1 { get; set; }
        public Nullable<decimal> GmWt_2 { get; set; }
        public string GmWt_Desc2 { get; set; }
        public Nullable<int> Calcium_mg { get; set; }
        public Nullable<decimal> Iron_mg { get; set; }
        public Nullable<decimal> Magnesium_mg { get; set; }
        public Nullable<int> Phosphorus_mg { get; set; }
        public Nullable<int> Potassium_mg { get; set; }
        public Nullable<int> Sodium_mg { get; set; }
        public Nullable<decimal> Zinc_mg { get; set; }
        public Nullable<decimal> Copper_mg { get; set; }
        public Nullable<decimal> Manganese_mg { get; set; }
        public Nullable<decimal> Selenium_µg { get; set; }
        public Nullable<decimal> Vit_C_mg { get; set; }
        public Nullable<decimal> Thiamin_mg { get; set; }
        public Nullable<decimal> Riboflavin_mg { get; set; }
        public Nullable<decimal> Niacin_mg { get; set; }
        public Nullable<decimal> Panto_Acid_mg { get; set; }
        public Nullable<decimal> Vit_B6_mg { get; set; }
        public Nullable<decimal> Folate_Tot_µg { get; set; }
        public Nullable<decimal> Choline_Tot__mg { get; set; }
        public Nullable<decimal> Vit_B12_µg { get; set; }
        public Nullable<int> Vit_A_IU { get; set; }
        public Nullable<decimal> Vit_A_RAE { get; set; }
        public Nullable<decimal> Retinol_µg { get; set; }
        public Nullable<decimal> Alpha_Carot_µg { get; set; }
        public Nullable<decimal> Beta_Carot_µg { get; set; }
        public Nullable<decimal> Beta_Crypt_µg { get; set; }
        public Nullable<decimal> Lycopene_µg { get; set; }
        public Nullable<decimal> Lut_Zea__µg { get; set; }
        public Nullable<decimal> Vit_E_mg { get; set; }
        public Nullable<decimal> Vit_D_µg { get; set; }
        public Nullable<decimal> Vit_D_IU { get; set; }
        public Nullable<decimal> Vit_K_µg { get; set; }
        public Nullable<int> Refuse_Pct { get; set; }
    
        public virtual Ingredients_Desc Ingredients_Desc { get; set; }
        public virtual ICollection<RecipeDetailsEntities> RecipeDetailsEntities { get; set; }
    }
}
