//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutritionEntities : DbContext
    {
        public NutritionEntities()
            : base("name=NutritionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<IngredientEntity> IngredientEntities { get; set; }
        public DbSet<Ingredients_Desc> Ingredients_Desc { get; set; }
        public DbSet<RecipeDetailsEntities> RecipeDetailsEntities { get; set; }
        public DbSet<RecipeEntity> RecipeEntities { get; set; }
    }
}
