//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeEntity
    {
        public RecipeEntity()
        {
            this.RecipeDetailsEntities = new HashSet<RecipeDetailsEntities>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PrepTime_m { get; set; }
        public Nullable<int> CookTime_m { get; set; }
        public Nullable<int> ReadyTime_m { get; set; }
        public string ImgUrl { get; set; }
        public string Directions { get; set; }
        public Nullable<decimal> Rating { get; set; }
    
        public virtual ICollection<RecipeDetailsEntities> RecipeDetailsEntities { get; set; }
    }
}
